"use client"

import { useState, useMemo } from "react"
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts"
import { formatUSD } from "@/lib/utils"
import { PeriodToggle, type Period } from "./period-toggle"
import { aggregateData } from "./aggregate"
import { ChartFrame } from "@/components/chart-frame"
import { useThemeColors } from "@/components/theme-provider"

const METHODOLOGY = `Spark Total Revenue captures every stream of income flowing to the protocol treasury:

SparkLend Net Interest: The protocol treasury's share of borrower interest payments in the SparkLend pool, determined by each asset's Reserve Factor.

SparkLend Flashloan: Premiums collected from flash loan operations on the SparkLend pool (typically 0.05% per flash loan).

Spark Liquidity Layer (SLL): Net yield generated by the ALM Proxy (0x1601...347E) deploying idle USDS/DAI into Morpho vaults, Aave V3, Ethena sUSDe, Curve pools and other integrations, less the funding cost paid to Sky. Negative days occur when funding costs exceed venue yields.

Distribution Rewards: Monthly USDS settlements paid by Sky's governance (MCD Pause Proxy, 0xbE28...38f3) into the Spark Proxy (0x3300...f8c4) via executive spell Cast. Sky pays these to Spark for hosting the sUSDS integration and channelling savings deposits. Each monthly payment is amortized across the days since the prior settlement; days after the most recent settlement carry forward at the trailing daily rate (estimated until the next settlement is executed).

Liquidation Fees: The protocol's share of liquidation penalties when undercollateralized SparkLend positions are wound down (~10% of the liquidation bonus).

Data is sourced from DefiLlama (spark-liquidity-layer and sparklend slugs) combined with on-chain event scanning for flash, liquidation, and Distribution Reward attribution.`

interface RevenueChartProps {
  daily: Array<{ date: number; netInterestIncome: number; flashloanFees: number; liquidationFees: number; sllRevenue: number; distributionRewards: number }>
}

const STREAMS = [
  { key: "netInterestIncome", label: "SparkLend Net Interest", color: "#3b82f6" },
  { key: "sllRevenue", label: "Spark Liquidity Layer", color: "#f59e0b" },
  { key: "distributionRewards", label: "Distribution Rewards", color: "#a855f7" },
  { key: "flashloanFees", label: "SparkLend Flashloan", color: "#06b6d4" },
  { key: "liquidationFees", label: "Liquidation", color: "#ef4444" },
]

function ChartTooltip({ active, payload, label }: any) {
  if (!active || !payload?.length) return null
  const items = payload.filter((p: any) => p.value !== 0 && p.value != null)
  const total = items.reduce((s: number, p: any) => s + p.value, 0)

  return (
    <div className="custom-tooltip min-w-[200px]">
      <p className="text-xs text-text-muted mb-1.5">{label}</p>
      {items.map((item: any) => (
        <div key={item.dataKey} className="flex items-center justify-between gap-4 mb-1">
          <div className="flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full" style={{ backgroundColor: item.fill || item.color }} />
            <span className="text-xs text-text-secondary">{STREAMS.find((s) => s.key === item.dataKey)?.label || item.dataKey}</span>
          </div>
          <span className="text-xs font-medium text-text-primary">{formatUSD(item.value)}</span>
        </div>
      ))}
      {items.length > 1 && (
        <div className="border-t border-card-border mt-1 pt-1 flex justify-between">
          <span className="text-xs text-text-secondary">Total</span>
          <span className="text-xs font-semibold text-text-primary">{formatUSD(total)}</span>
        </div>
      )}
    </div>
  )
}

export function RevenueChart({ daily }: RevenueChartProps) {
  const colors = useThemeColors()
  const [period, setPeriod] = useState<Period>("M")
  const [visible, setVisible] = useState<Record<string, boolean>>({
    netInterestIncome: true,
    sllRevenue: true,
    distributionRewards: true,
    flashloanFees: true,
    liquidationFees: true,
  })

  const chartData = useMemo(
    () => aggregateData(daily, period, STREAMS.map((s) => s.key)),
    [daily, period]
  )

  const toggleStream = (key: string) => {
    setVisible((v) => ({ ...v, [key]: !v[key] }))
  }

  const chartActions = (
    <PeriodToggle selected={period} onChange={setPeriod} />
  )

  return (
    <ChartFrame
      title="Spark Total Revenue"
      subtitle="SparkLend, Spark Liquidity Layer, Distribution Rewards and Liquidation, after funding cost"
      units="USD"
      source="DefiLlama (sparklend + spark-liquidity-layer) + on-chain USDS mints"
      methodology={METHODOLOGY}
      actions={chartActions}
      height={320}
    >
      <div className="flex items-center gap-4 px-1 mb-2 mt-1">
        {STREAMS.map((s) => (
          <button
            key={s.key}
            onClick={() => toggleStream(s.key)}
            className={`flex items-center gap-1.5 text-[11px] transition-opacity ${visible[s.key] ? "opacity-100" : "opacity-40"}`}
          >
            <span className="w-2.5 h-2.5 rounded-sm" style={{ backgroundColor: s.color }} />
            <span className="text-text-secondary">{s.label}</span>
          </button>
        ))}
      </div>

      <div style={{ height: 280 }} className="w-full">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData} margin={{ top: 5, right: 5, left: 5, bottom: 0 }}>
            <XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 9, fill: colors.textMuted }} interval="preserveStartEnd" minTickGap={30} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: colors.textMuted }} tickFormatter={(v) => formatUSD(v)} width={60} />
            <Tooltip content={<ChartTooltip />} cursor={{ fill: "rgba(255,255,255,0.03)" }} />
            {STREAMS.map(
              (s) =>
                visible[s.key] && (
                  <Bar key={s.key} dataKey={s.key} stackId="1" fill={s.color} radius={[0, 0, 0, 0]} />
                )
            )}
          </BarChart>
        </ResponsiveContainer>
      </div>
    </ChartFrame>
  )
}
